#!/bin/sh

# Get a list of staged files
staged_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx)$')

if [ -n "$staged_files" ]; then
    echo "Running Deno formatter and linter on staged files..."

    # Run deno fmt
    echo "$staged_files" | xargs deno fmt

    # Run deno lint --fix
    echo "$staged_files" | xargs deno lint --fix

    # Add the formatted and linted files back to the staging area
    echo "$staged_files" | xargs git add

    echo "Deno formatter and linter completed."
else
    echo "No supported files to format or lint."
fi

# If everything succeeded, exit with 0
exit 0
